- hosts: all
  name: HPE Proliant agent-ilo job
  tasks:

    - name: Create workspace directory to run agent-ilo
      file:
        path: '/tmp/agent-ilo'
        state: directory

    - block:
        - name: Cloning devstack-gate for agent-ilo
          shell: cd /tmp/agent-ilo; git clone https://github.com/hpproliant/HPE-CI-JOBS.git

        - name: Configure molten
          shell: sudo bash /tmp/agent-ilo/HPE-CI-JOBS/molteniron/configure_molten

        - name: Generate MoltenIron Id for node
          command: uuidgen
          register: uuid

        - name: Allocating test node
          command: /tmp/agent-ilo/HPE-CI-JOBS/molteniron/allocate_molten.py {{ uuid.stdout }} Gen9

        - name: Running agent-ilo
          shell: bash /tmp/agent-ilo/HPE-CI-JOBS/agent-ilo/gate.sh

      always:
        - name: Deallocating test node
          shell: /tmp/agent-ilo/HPE-CI-JOBS/molteniron/release_molten.py {{ uuid.stdout }}
