- hosts: all
  name: HPE Proliant redfish driver job
  tasks:

    - name: Create workspace directory to run redfish-driver
      file:
        path: '/tmp/redfish-driver'
        state: directory

    - block:
        - name: Cloning devstack-gate for redfish-driver
          shell: cd /tmp/redfish-driver; git clone https://github.com/hpproliant/HPE-CI-JOBS.git

        - name: Configure molten
          shell: sudo bash /tmp/redfish-driver/HPE-CI-JOBS/molteniron/configure_molten

        - name: Running dhclient
          shell: sudo dhclient

        - name: Generate MoltenIron Id for node
          command: uuidgen
          register: uuid

        - name: Allocating test node
          command: /tmp/redfish-driver/HPE-CI-JOBS/molteniron/allocate_molten.py {{ uuid.stdout }} Ironic_Redfish

        - name: Running redfish-driver
          shell: bash /tmp/redfish-driver/HPE-CI-JOBS/redfish-driver/gate.sh

      always:
        - name: Deallocating test node
          shell: /tmp/redfish-driver/HPE-CI-JOBS/molteniron/release_molten.py {{ uuid.stdout }}
