- hosts: all
  name: HPE Proliant ilo5 driver job
  tasks:

    - name: Create workspace directory to run ilo5-driver
      file:
        path: '/tmp/uefi-https'
        state: directory

    - block:
        - name: Cloning devstack-gate for ilo5-driver
          shell: cd /tmp/uefi-https; git clone https://github.com/hpproliant/HPE-CI-JOBS.git

        - name: Clone Projects
          shell: /tmp/uefi-https/HPE-CI-JOBS/clone_project.sh

        - name: Cherry pick
          shell: cd /opt/stack/ironic; git config --global user.email "proliantutils@gmail.com"; git config --global user.name "proliantci"; git fetch https://review.opendev.org/openstack/ironic {{zuul.ref}} && git cherry-pick FETCH_HEAD

        - name: Preparing gate
          shell: bash /tmp/uefi-https/HPE-CI-JOBS/ilo5-uefi-https/prepare_gate.sh

        - name: Configure molten
          shell: sudo bash /tmp/uefi-https/HPE-CI-JOBS/molteniron/configure_molten

        - name: Running dhclient
          shell: sudo dhclient

        - name: Generate MoltenIron Id for node
          command: uuidgen
          register: uuid

        - name: Allocating test node
          command: /tmp/uefi-https/HPE-CI-JOBS/molteniron/allocate_molten.py {{ uuid.stdout }} Ironic_Gen10

        - name: Running redfish-driver
          shell: bash /tmp/uefi-https/HPE-CI-JOBS/ilo5-uefi-https/gate.sh

      always:
        - name: Deallocating test node
          shell: /tmp/uefi-https/HPE-CI-JOBS/molteniron/release_molten.py {{ uuid.stdout }}
