- hosts: all
  name: HPE Proliant pxe-ilo job
  tasks:

    - name: Create workspace directory to run pxe-ilo
      file:
        path: '/tmp/pxe-ilo'
        state: directory

    - block:
        - name: Clonning devstack-gate for pxe-ilo
          shell: cd /tmp/pxe-ilo; git clone https://github.com/hpproliant/HPE-CI-JOBS.git

        - name: Preparing gate
          shell: bash /tmp/pxe-ilo/HPE-CI-JOBS/pxe-ilo/prepare_gate.sh

        - name: Cherry pick
          shell: cd /opt/stack/ironic; git config --global user.email "proliantutils@gmail.com"; git config --global user.name "proliantci"; git fetch https://review.opendev.org/openstack/ironic {{zuul.ref}} && git cherry-pick FETCH_HEAD

        - name: Configure molten
          shell: sudo bash /tmp/pxe-ilo/HPE-CI-JOBS/molteniron/configure_molten

        - name: Running dhclient
          shell: sudo dhclient

        - name: Generate MoltenIron Id for node
          command: uuidgen
          register: uuid

        - name: Allocating test node
          command: /tmp/pxe-ilo/HPE-CI-JOBS/molteniron/allocate_molten.py {{ uuid.stdout }} Pxe

        - name: Running pxe-ilo
          shell: bash /tmp/pxe-ilo/HPE-CI-JOBS/pxe-ilo/gate.sh

      always:
        - name: Deallocating test node
          shell: /tmp/pxe-ilo/HPE-CI-JOBS/molteniron/release_molten.py {{ uuid.stdout }}

