- hosts: all
  name: HPE Proliant redfish pxe driver job
  tasks:

    - name: Create workspace directory to run redfish-pxe-driver
      file:
        path: '/tmp/redfish-pxe-driver'
        state: directory

    - block:
        - name: Cloning devstack-gate for redfish-driver
          shell: cd /tmp/redfish-pxe-driver; git clone https://github.com/hpproliant/HPE-CI-JOBS.git

        - name: Clone Projects
          shell: /tmp/redfish-pxe-driver/HPE-CI-JOBS/clone_project.sh

        - name: Cherry pick
          shell: cd /opt/stack/ironic; git config --global user.email "proliantutils@gmail.com"; git config --global user.name "proliantci"; git fetch https://review.opendev.org/openstack/ironic {{zuul.ref}} && git cherry-pick FETCH_HEAD

        - name: Preparing gate
          shell: bash /tmp/redfish-pxe-driver/HPE-CI-JOBS/redfish-pxe-driver/prepare_gate.sh

        - name: Configure molten
          shell: sudo bash /tmp/redfish-pxe-driver/HPE-CI-JOBS/molteniron/configure_molten

        - name: Generate MoltenIron Id for node
          command: uuidgen
          register: uuid

        - name: Allocating test node
          command: /tmp/redfish-pxe-driver/HPE-CI-JOBS/molteniron/allocate_molten.py {{ uuid.stdout }} Redfish

        - name: Running redfish-driver
          shell: bash /tmp/redfish-pxe-driver/HPE-CI-JOBS/redfish-pxe-driver/gate.sh

      always:
        - name: Deallocating test node
          shell: /tmp/redfish-pxe-driver/HPE-CI-JOBS/molteniron/release_molten.py {{ uuid.stdout }}
