- hosts: all
  name: HPE Proliant iscsi-ilo job
  tasks:

    - name: Create workspace directory to run iscsi-ilo
      file:
        path: '/tmp/iscsi-ilo'
        state: directory

    - block:
        - name: Cloning devstack-gate for iscsi-ilo
          shell: cd /tmp/iscsi-ilo; git clone https://github.com/hpproliant/HPE-CI-JOBS.git

        - name: Clone Projects
          shell: /tmp/iscsi-ilo/HPE-CI-JOBS/clone_project.sh

        - name: Cherry pick
          shell: cd /opt/stack/ironic; git config --global user.email "proliantutils@gmail.com"; git config --global user.name "proliantci"; git fetch https://review.opendev.org/openstack/ironic {{zuul.ref}} && git cherry-pick FETCH_HEAD

        - name: Preparing gate
          shell: /tmp/iscsi-ilo/HPE-CI-JOBS/iscsi-ilo/prepare_gate.sh

        - name: Configure molten
          shell: sudo bash /tmp/iscsi-ilo/HPE-CI-JOBS/molteniron/configure_molten

        - name: Generate MoltenIron Id for node
          command: uuidgen
          register: uuid

        - name: Allocating test node
          command: /tmp/iscsi-ilo/HPE-CI-JOBS/molteniron/allocate_molten.py {{ uuid.stdout }} Iscsi

        - name: Running iscsi-ilo
          shell: bash /tmp/iscsi-ilo/HPE-CI-JOBS/iscsi-ilo/gate.sh

      always:
        - name: Deallocating test node
          shell: /tmp/iscsi-ilo/HPE-CI-JOBS/molteniron/release_molten.py {{ uuid.stdout }}
