- hosts: all
  tasks:


    - name: Set log path for a change
      when: zuul.change is defined
      set_fact:
        log_path: "{{ zuul.change[-2:] }}/{{ zuul.change }}/{{ zuul.patchset }}/{{ zuul.pipeline }}/{{ zuul.job }}/{{ zuul.build[:7] }}"

    - name: Set log path for a ref update
      when: zuul.newrev is defined
      set_fact:
        log_path: "{{ zuul.newrev[-2:] }}/{{ zuul.newrev }}/{{ zuul.pipeline }}/{{ zuul.job }}/{{ zuul.build[:7] }}"

    - name: Set log path for a periodic job
      when: zuul.change is not defined and zuul.newrev is not defined
      set_fact:
        log_path: "{{ zuul.pipeline }}/{{ zuul.job }}/{{ zuul.build[:7] }}"

    - name: Preparing file for logs
      tempfile:
        state: file
      register: tmpe
      no_log: true

    - name: Create log directory
      file:
         path: /tmp/new_zuul
         state: directory
         owner: ubuntu
         group: ubuntu
         mode: 0775     

    - block:
        - name: Preparing logs
          copy:
            content: |
              ssh -i /home/ubuntu/zuul_id_rsa -o StrictHostKeyChecking=no zuul@169.16.1.54 "sudo chown -R zuul.zuul {{ zuul.executor.log_root }}"
              ssh -i /home/ubuntu/zuul_id_rsa -o StrictHostKeyChecking=no zuul@169.16.1.54 "sudo chmod -R 0777 /tmp; sudo chown -R zuul.zuul /tmp"
              scp -i /home/ubuntu/zuul_id_rsa -o StrictHostKeyChecking=no -r zuul@169.16.1.54:{{ zuul.executor.log_root }} /tmp/new_zuul/
              sudo journalctl -u devstack@dstat.service >>/tmp/new_zuul/dstat.service 2>/dev/null
              sudo journalctl -u devstack@etcd.service >>/tmp/new_zuul/etcd.service 2>/dev/null
              sudo journalctl -u devstack@g-api.service >>/tmp/new_zuul/g-api.service 2>/dev/null
              sudo journalctl -u devstack@g-reg.service >>/tmp/new_zuul/g-reg.service 2>/dev/null
              sudo journalctl -u devstack@ir-api.service >>/tmp/new_zuul/ir-api.service 2>/dev/null
              sudo journalctl -u devstack@ir-cond.service >>/tmp/new_zuul/ir-cond.service 2>/dev/null
              sudo journalctl -u devstack@keystone.service >>/tmp/new_zuul/keystone.service 2>/dev/null
              sudo journalctl -u devstack@q-l3.service >>/tmp/new_zuul/q-l3.service 2>/dev/null
              sudo journalctl -u devstack@q-agt.service >>/tmp/new_zuul/q-agt.service 2>/dev/null
              sudo journalctl -u devstack@q-dhcp.service >>/tmp/new_zuul/q-dhcp.service 2>/dev/null
              sudo journalctl -u devstack@q-meta.service >>/tmp/new_zuul/q-meta.service 2>/dev/null
              sudo journalctl -u devstack@s-account.service >>/tmp/new_zuul/s-account.service 2>/dev/null
              sudo journalctl -u devstack@q-svc.service >>/tmp/new_zuul/q-svc.service 2>/dev/null
              sudo journalctl -u devstack@s-container-sync.service >>/tmp/new_zuul/s-container-sync.service 2>/dev/null
              sudo journalctl -u devstack@s-container.service >>/tmp/new_zuul/s-container.service 2>/dev/null
              sudo journalctl -u devstack@s-object.service >>/tmp/new_zuul/s-object.service 2>/dev/null
              sudo journalctl -u devstack@s-proxy.service >>/tmp/new_zuul/s-proxy.service 2>/dev/null
              mkdir -p /tmp/new_zuul/etc
              sudo cp -r /etc/glance/ /etc/ironic/ /etc/keystone /etc/neutron /etc/swift /tmp/new_zuul/etc/
              sudo cp /opt/stack/tempest/etc/tempest.conf /tmp/new_zuul/etc/
              if [ -d /tmp/devstack_logs/ ]; then
                 mv /tmp/devstack_logs /tmp/new_zuul/
                 sudo cp /opt/stack/devstack/local.conf /tmp/new_zuul/devstack_logs
              fi
              echo "commiting logs"
              cd /tmp
              export GIT_SSH_COMMAND="ssh -i ~/zuul_id_rsa"
              git clone git@github.com:hpproliant/hpeproliant.github.io.git
              ls hpeproliant.github.io
              count=0
              while [ $count -lt 5 ] ; do
                echo "Refresh log repository"
                cd /tmp/hpeproliant.github.io
                git checkout .
                git pull
                mkdir -p /tmp/hpeproliant.github.io/logs/{{ log_path }}
                cp -R /tmp/new_zuul/ /tmp/hpeproliant.github.io/logs/{{ log_path }}
                python logs2html.py /tmp/hpeproliant.github.io
                git config user.email "proliantutils@gmail.com"
                git config user.name hpproliant
                git add .
                git commit -m "Commited {{ log_path }}"
                git push
                if [ $? -eq 0 ]; then
                  break
                fi
                let count=count+1
                sleep 30
                sleep $((1 + RANDOM % 60))
              done

            dest: "{{ tmpe.path }}"
            mode: 0777
          no_log: true
          become: true

        - name: Posting logs to logserver
          shell: bash {{ tmpe.path }}
      always:
        - name: Post logs to gerrit
          delegate_to: localhost
          zuul_return:
            data:
             zuul:
                log_url: "https://hpproliant.github.io/hpeproliant.github.io/logs/{{ log_path }}/{{ zuul.build[:7] }}.html"
